package br.com.sisnema.financeiroweb.model;

// Generated 04/08/2015 22:19:49 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", schema = "public")
public class Cliente implements java.io.Serializable {

	private ClienteId id;
	private Colaborador colaborador;
	private boolean situacao;

	public Cliente() {
	}

	public Cliente(Colaborador colaborador, boolean situacao) {
		this.colaborador = colaborador;
		this.situacao = situacao;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "empresa", column = @Column(name = "empresa", nullable = false)),
			@AttributeOverride(name = "colaborador", column = @Column(name = "colaborador", nullable = false)) })
	public ClienteId getId() {
		return this.id;
	}

	public void setId(ClienteId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Colaborador getColaborador() {
		return this.colaborador;
	}

	public void setColaborador(Colaborador colaborador) {
		this.colaborador = colaborador;
	}

	@Column(name = "situacao", nullable = false)
	public boolean isSituacao() {
		return this.situacao;
	}

	public void setSituacao(boolean situacao) {
		this.situacao = situacao;
	}

}
