package br.com.sisnema.financeiroweb.model;

// Generated 04/08/2015 22:19:49 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "estado", schema = "public")
public class Estado implements java.io.Serializable {

	private String codigo;
	private String descricao;
	private Set<Municipio> municipios = new HashSet<Municipio>(0);

	public Estado() {
	}

	public Estado(String codigo, String descricao) {
		this.codigo = codigo;
		this.descricao = descricao;
	}

	public Estado(String codigo, String descricao, Set<Municipio> municipios) {
		this.codigo = codigo;
		this.descricao = descricao;
		this.municipios = municipios;
	}

	@Id
	@Column(name = "codigo", unique = true, nullable = false, length = 2)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descricao", nullable = false, length = 50)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<Municipio> getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Set<Municipio> municipios) {
		this.municipios = municipios;
	}

}
