package br.com.sisnema.financeiroweb.model;

// Generated 04/08/2015 22:19:49 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FilialId generated by hbm2java
 */
@Embeddable
public class FilialId implements java.io.Serializable {

	private int empresa;
	private int codigo;

	public FilialId() {
	}

	public FilialId(int empresa, int codigo) {
		this.empresa = empresa;
		this.codigo = codigo;
	}

	@Column(name = "empresa", nullable = false)
	public int getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(int empresa) {
		this.empresa = empresa;
	}

	@Column(name = "codigo", nullable = false)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FilialId))
			return false;
		FilialId castOther = (FilialId) other;

		return (this.getEmpresa() == castOther.getEmpresa())
				&& (this.getCodigo() == castOther.getCodigo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEmpresa();
		result = 37 * result + this.getCodigo();
		return result;
	}

}
