package br.com.sisnema.financeiroweb.model;

// Generated 04/08/2015 22:19:49 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Filial generated by hbm2java
 */
@Entity
@Table(name = "filial", schema = "public")
public class Filial implements java.io.Serializable {

	private FilialId id;
	private Empresa empresa;
	private Municipio municipio;
	private String apelido;
	private String razaoSocial;
	private String nomeFantasia;
	private String endereco;
	private Integer numero;
	private String complemento;
	private String bairro;
	private String cep;
	private Serializable telefone;
	private String celular;
	private String tipoInscricao;
	private String incricao;
	private String inscricaoEstadual;
	private String inscricaoMunicipal;
	private Date inicioAtividade;
	private Date fechamentoAtividade;
	private String email;
	private boolean situacao;

	public Filial() {
	}

	public Filial(FilialId id, Empresa empresa, String razaoSocial,
			boolean situacao) {
		this.id = id;
		this.empresa = empresa;
		this.razaoSocial = razaoSocial;
		this.situacao = situacao;
	}

	public Filial(FilialId id, Empresa empresa, Municipio municipio,
			String apelido, String razaoSocial, String nomeFantasia,
			String endereco, Integer numero, String complemento, String bairro,
			String cep, Serializable telefone, String celular,
			String tipoInscricao, String incricao, String inscricaoEstadual,
			String inscricaoMunicipal, Date inicioAtividade,
			Date fechamentoAtividade, String email, boolean situacao) {
		this.id = id;
		this.empresa = empresa;
		this.municipio = municipio;
		this.apelido = apelido;
		this.razaoSocial = razaoSocial;
		this.nomeFantasia = nomeFantasia;
		this.endereco = endereco;
		this.numero = numero;
		this.complemento = complemento;
		this.bairro = bairro;
		this.cep = cep;
		this.telefone = telefone;
		this.celular = celular;
		this.tipoInscricao = tipoInscricao;
		this.incricao = incricao;
		this.inscricaoEstadual = inscricaoEstadual;
		this.inscricaoMunicipal = inscricaoMunicipal;
		this.inicioAtividade = inicioAtividade;
		this.fechamentoAtividade = fechamentoAtividade;
		this.email = email;
		this.situacao = situacao;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "empresa", column = @Column(name = "empresa", nullable = false)),
			@AttributeOverride(name = "codigo", column = @Column(name = "codigo", nullable = false)) })
	public FilialId getId() {
		return this.id;
	}

	public void setId(FilialId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "empresa", nullable = false, insertable = false, updatable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "municipio")
	public Municipio getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(Municipio municipio) {
		this.municipio = municipio;
	}

	@Column(name = "apelido", length = 50)
	public String getApelido() {
		return this.apelido;
	}

	public void setApelido(String apelido) {
		this.apelido = apelido;
	}

	@Column(name = "razaoSocial", nullable = false, length = 80)
	public String getRazaoSocial() {
		return this.razaoSocial;
	}

	public void setRazaoSocial(String razaoSocial) {
		this.razaoSocial = razaoSocial;
	}

	@Column(name = "nomeFantasia", length = 80)
	public String getNomeFantasia() {
		return this.nomeFantasia;
	}

	public void setNomeFantasia(String nomeFantasia) {
		this.nomeFantasia = nomeFantasia;
	}

	@Column(name = "endereco", length = 80)
	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	@Column(name = "numero")
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Column(name = "complemento", length = 50)
	public String getComplemento() {
		return this.complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	@Column(name = "bairro", length = 50)
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "cep", length = 8)
	public String getCep() {
		return this.cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	@Column(name = "telefone")
	public Serializable getTelefone() {
		return this.telefone;
	}

	public void setTelefone(Serializable telefone) {
		this.telefone = telefone;
	}

	@Column(name = "celular", length = 15)
	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	@Column(name = "tipoInscricao", length = 4)
	public String getTipoInscricao() {
		return this.tipoInscricao;
	}

	public void setTipoInscricao(String tipoInscricao) {
		this.tipoInscricao = tipoInscricao;
	}

	@Column(name = "incricao", length = 14)
	public String getIncricao() {
		return this.incricao;
	}

	public void setIncricao(String incricao) {
		this.incricao = incricao;
	}

	@Column(name = "inscricaoEstadual", length = 20)
	public String getInscricaoEstadual() {
		return this.inscricaoEstadual;
	}

	public void setInscricaoEstadual(String inscricaoEstadual) {
		this.inscricaoEstadual = inscricaoEstadual;
	}

	@Column(name = "inscricaoMunicipal", length = 20)
	public String getInscricaoMunicipal() {
		return this.inscricaoMunicipal;
	}

	public void setInscricaoMunicipal(String inscricaoMunicipal) {
		this.inscricaoMunicipal = inscricaoMunicipal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "inicioAtividade", length = 13)
	public Date getInicioAtividade() {
		return this.inicioAtividade;
	}

	public void setInicioAtividade(Date inicioAtividade) {
		this.inicioAtividade = inicioAtividade;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechamentoAtividade", length = 13)
	public Date getFechamentoAtividade() {
		return this.fechamentoAtividade;
	}

	public void setFechamentoAtividade(Date fechamentoAtividade) {
		this.fechamentoAtividade = fechamentoAtividade;
	}

	@Column(name = "email", length = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "situacao", nullable = false)
	public boolean isSituacao() {
		return this.situacao;
	}

	public void setSituacao(boolean situacao) {
		this.situacao = situacao;
	}

}
