package br.com.sisnema.financeiroweb.model;

// Generated 04/08/2015 22:40:19 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Usuariopermissao generated by hbm2java
 */
@Entity
@Table(name = "usuariopermissao", schema = "public")
public class Usuariopermissao implements java.io.Serializable {

	private UsuariopermissaoId id;
	private Usuario usuario;
	private String permissao;

	public Usuariopermissao() {
	}

	public Usuariopermissao(Usuario usuario) {
		this.usuario = usuario;
	}

	public Usuariopermissao(Usuario usuario, String permissao) {
		this.usuario = usuario;
		this.permissao = permissao;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "usuario", column = @Column(name = "usuario", nullable = false)),
			@AttributeOverride(name = "empresa", column = @Column(name = "empresa", nullable = false)) })
	public UsuariopermissaoId getId() {
		return this.id;
	}

	public void setId(UsuariopermissaoId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "permissao", length = 50)
	public String getPermissao() {
		return this.permissao;
	}

	public void setPermissao(String permissao) {
		this.permissao = permissao;
	}

}
