package br.com.sisnema.financeiroweb.model;

// Generated 04/08/2015 22:40:19 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuariopermissaoId generated by hbm2java
 */
@Embeddable
public class UsuariopermissaoId implements java.io.Serializable {

	private int usuario;
	private int empresa;

	public UsuariopermissaoId() {
	}

	public UsuariopermissaoId(int usuario, int empresa) {
		this.usuario = usuario;
		this.empresa = empresa;
	}

	@Column(name = "usuario", nullable = false)
	public int getUsuario() {
		return this.usuario;
	}

	public void setUsuario(int usuario) {
		this.usuario = usuario;
	}

	@Column(name = "empresa", nullable = false)
	public int getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(int empresa) {
		this.empresa = empresa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuariopermissaoId))
			return false;
		UsuariopermissaoId castOther = (UsuariopermissaoId) other;

		return (this.getUsuario() == castOther.getUsuario())
				&& (this.getEmpresa() == castOther.getEmpresa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUsuario();
		result = 37 * result + this.getEmpresa();
		return result;
	}

}
